# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_bill_no_alter_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='discount',
        ),
    ]



